# Generated by Django 4.1.5 on 2023-01-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
